name: Create Release .zip Files

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"

jobs:
  package-and-publish:
    name: Create and publish .zip files for release tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Zip map files
      run: |
        zip ./select_maps.zip ./maps/select/*.map
        zip ./all_maps.zip ./maps/select/*.map ./maps/general/*.map
    - name: Save release files
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          select_maps.zip
          all_maps.zip
